/** Data contract for the static JSON generated by scripts/build-data.mjs. */

export type ElectionType = 'PRIMARY' | 'GENERAL' | 'SPECIAL';

export interface ElectionMeta {
  date: string; // YYYY-MM-DD
  electionType: ElectionType;
  totalAmount: number;
  contributionCount: number;
  candidateCount: number;
  raceCount: number;
}

export interface ElectionsIndex {
  generatedAt: string;
  source: string;
  elections: ElectionMeta[];
}

export interface TopCandidate {
  name: string;
  slug: string;
  office: string;
  location: string;
  total: number;
  count: number;
}

/** Named donors only — synthetic rows are excluded by the pipeline. */
export interface TopDonor {
  key: string;
  name: string;
  city: string;
  state: string;
  employer: string;
  /** pipeline-normalized canonical employer key ('' when junk/empty) */
  employerKey: string;
  occupation: string;
  total: number;
  count: number;
  recipientCount: number;
}

export interface TopSelfFunder {
  candidateSlug: string;
  name: string;
  office: string;
  location: string;
  total: number;
  count: number;
}

/** Entry shape shared by summary.topEmployers and e/<date>/employers.json. */
export interface EmployerRollup {
  /** pipeline-normalized canonical key */
  key: string;
  /** canonical display name */
  name: string;
  total: number;
  count: number;
  donorCount: number;
}

export interface OfficeTotal {
  office: string;
  total: number;
}

export interface ContributionTypeTotal {
  type: string;
  total: number;
}

export interface MonthTotal {
  month: string; // YYYY-MM
  total: number;
}

export interface ElectionSummary {
  date: string;
  electionType: ElectionType;
  totalAmount: number;
  contributionCount: number;
  candidateCount: number;
  raceCount: number;
  donorCount: number;
  namedDonorCount: number;
  /** dollar total of candidate self-funding */
  selfFundingTotal: number;
  /** dollar total of unitemized small-dollar bundles */
  unitemizedTotal: number;
  topCandidates: TopCandidate[];
  topDonors: TopDonor[];
  topSelfFunders: TopSelfFunder[];
  topEmployers: EmployerRollup[];
  byOffice: OfficeTotal[];
  byContributionType: ContributionTypeTotal[];
  monthly: MonthTotal[];
}

export interface RaceCandidate {
  name: string;
  slug: string;
  total: number;
  count: number;
}

export interface Race {
  office: string;
  location: string;
  slug: string;
  total: number;
  count: number;
  candidates: RaceCandidate[];
}

export interface DonorRecipient {
  slug: string;
  name: string;
  office: string;
  location: string;
  total: number;
  count: number;
}

export interface Donor {
  key: string;
  name: string;
  city: string;
  state: string;
  employer: string;
  /** pipeline-normalized canonical employer key ('' when junk/empty) */
  employerKey: string;
  occupation: string;
  total: number;
  count: number;
  recipients: DonorRecipient[];
}

/**
 * Entry shape of e/<date>/donors-lite.json — donors.json minus the recipients
 * arrays, so the search/employer pages don't pull the multi-MB full corpus.
 */
export type DonorLite = Omit<Donor, 'recipients'> & { recipientCount: number };

/** Compact per-contribution record inside candidate shards. */
export interface Contribution {
  /** donor identity key */
  d: string;
  /** contributor name */
  n: string;
  /** amount */
  a: number;
  /** contribution type (INDIVIDUAL / CANDIDATE / UNITEMIZED / ...) */
  t: string;
  /** mode (DIRECT / EVENT_FUNDRAISING / LOAN / ...) */
  m: string;
  /** city */
  c: string;
  /** state */
  s: string;
  /** zip */
  z: string;
  /** employer */
  e: string;
  /** occupation */
  o: string;
  /** receipt date M/D/YYYY */
  r: string;
  /** in-kind description */
  k: string;
}

export interface CandidateFile {
  name: string;
  office: string;
  location: string;
  slug: string;
  total: number;
  count: number;
  contributions: Contribution[];
}
